name: ticky
description: "A new Flutter project."
publish_to: 'none'

version: 2.1.1+27

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  #fonts
  google_fonts: ^6.2.1

  #Firebase
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  firebase_analytics: ^11.5.2
  firebase_auth: ^5.6.2
  timezone: ^0.10.1
  currency_picker: ^2.0.21
  lottie: ^3.3.1
  flutter_image_stack: ^0.0.7
  flutter_speed_dial: ^7.0.0
  country_code_picker_plus: ^0.1.0+1
  pinput: ^5.0.1
  google_maps_flutter: ^2.12.3
  pin_code_fields: ^8.0.1
  flutter_local_notifications: ^18.0.1

  firebase_messaging: ^15.2.9

  #RestApi
  html: ^0.15.6
  http: ^1.4.0

  #location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  location: ^8.0.1

  # utils
  nb_utils: ^7.1.6
  ag_widgets: ^1.1.3
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  pdfx: ^2.9.2
  photo_view: ^0.15.0
  upgrader: ^11.4.0
  dropdown_search: ^6.0.2
  syncfusion_flutter_pdf: ^30.1.38
  syncfusion_flutter_pdfviewer: ^30.1.38
  syncfusion_flutter_signaturepad: ^30.1.38
  syncfusion_flutter_datepicker: ^30.1.38
  table_calendar: ^3.2.0

#  google_maps_apis: ^1.1.1

  # State Managements
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0

  #File Picket
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  local_auth: ^2.3.0
  flutter_launcher_icons: ^0.14.4
  image_cropper: ^9.1.0
  package_info_plus: ^8.3.0
#  background_location_tracker: ^1.5.0
#  flutter_background_geolocation: ^4.16.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  mobx_codegen: ^2.7.1
#  dart run build_runner build --delete-conflicting-outputs
#  flutter build appbundle --flavor production -t lib/flavors/main-production.dart

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher-playstore.png"

dependency_overrides:
  intl: ^0.20.2
  device_info_plus: ^11.5.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/files/
    - assets/images/
    - assets/lottie/
